"use client";

import { useState } from "react";
import styles from "./FAQ.module.css";

const items = [
  ["Qu'est-ce que le parrainage ?", "Le parrainage permet à une personne de recommander un service, une banque, une assurance ou une autre entreprise à un proche grâce à un lien ou un code de parrainage.\n\nLorsque vous utilisez ce lien ou ce code et que vous réalisez les actions demandées par le partenaire, vous pouvez bénéficier d'une prime ou d'un avantage.\n\nAvec Parrainio, vous pouvez en plus bénéficier d'un reversement supplémentaire lorsque celui-ci est proposé sur l'offre."],
  ["Qu'est-ce qu'un lien ou un code de parrainage ?", "Un lien de parrainage est un lien personnalisé permettant au partenaire de reconnaître que votre inscription vient d'un parrain.\n\nUn code de parrainage fonctionne de la même manière : il doit généralement être renseigné au moment de l'inscription ou lors de la commande.\n\nPour profiter correctement de l'offre, utilisez toujours le lien ou le code indiqué sur la fiche Parrainio et respectez les conditions propres à l'offre."],
  ["Comment profiter d'une offre de parrainage ?", "C'est très simple :\n\n1. Choisissez une offre sur Parrainio.\n2. Consultez les conditions de l'offre.\n3. Cliquez sur le lien de parrainage ou utilisez le code indiqué.\n4. Réalisez les actions demandées par le partenaire.\n5. Une fois les conditions validées, vous bénéficiez de l'avantage prévu.\n\nLorsque l'offre prévoit un reversement Parrainio, celui-ci vient s'ajouter à l'avantage proposé par le partenaire."],
  ["Quelle est la différence entre la prime partenaire et le reversement Parrainio ?", "La prime partenaire est l'avantage proposé directement par la marque ou le service que vous rejoignez.\n\nLe reversement Parrainio est un avantage supplémentaire que Parrainio vous reverse lorsque l'offre le permet.\n\nPar exemple, une offre peut proposer une prime de 50 € et Parrainio peut vous reverser 10 € supplémentaires.\n\nVous bénéficiez alors de la prime partenaire + du reversement Parrainio."],
  ["Pourquoi Parrainio reverse-t-il une partie de sa rémunération ?", "Lorsqu'une personne utilise un lien de parrainage, Parrainio peut percevoir une rémunération ou une commission.\n\nPlutôt que de conserver systématiquement cette rémunération, Parrainio choisit d'en reverser une partie aux utilisateurs sur les offres concernées.\n\nC'est ce qui permet de proposer un avantage supplémentaire au-delà de la prime partenaire."],
  ["Pourquoi choisir Parrainio ?", "Parrainio permet de comparer facilement de nombreuses offres de parrainage au même endroit.\n\nVous pouvez retrouver les principales informations de chaque offre, les conditions à respecter et, lorsque cela est prévu, le montant supplémentaire reversé par Parrainio.\n\nL'objectif est simple : vous permettre de profiter plus facilement des offres de parrainage et de maximiser vos avantages."],
  ["Parrainio reverse-t-il vraiment de l'argent en plus ?", "Oui. Lorsque la fiche d'une offre indique un reversement Parrainio, celui-ci correspond à un avantage supplémentaire prévu par Parrainio.\n\nLe montant et les conditions peuvent varier selon l'offre.\n\nLe montant affiché dans « PARRAINIO REVERSE EN PLUS » correspond au montant ou au fonctionnement du reversement indiqué sur la fiche."],
  ["Les offres de parrainage sont-elles toutes identiques ?", "Non.\n\nChaque partenaire définit ses propres conditions : montant de la prime, dépôt minimum, achat, abonnement, durée, conditions d'éligibilité, etc.\n\nC'est pourquoi il est important de consulter les conditions spécifiques de chaque offre avant de s'inscrire.\n\nParrainio affiche les informations disponibles directement sur chaque fiche d'offre."],
  ["Puis-je utiliser plusieurs offres de parrainage ?", "Oui, vous pouvez profiter de différentes offres lorsque vous remplissez les conditions propres à chacune d'entre elles.\n\nChaque offre est indépendante : il faut donc consulter les conditions et utiliser le lien ou le code de parrainage correspondant à l'offre choisie."],
  ["Quand vais-je recevoir ma prime ?", "Le délai dépend du partenaire et des conditions de l'offre.\n\nCertaines primes sont attribuées rapidement, tandis que d'autres nécessitent une validation, un achat, un dépôt, une période d'attente ou la réalisation de plusieurs étapes.\n\nConsultez toujours les conditions indiquées sur la fiche de l'offre pour connaître les modalités applicables."],
  ["Que dois-je faire si mon parrainage n'est pas pris en compte ?", "Vérifiez d'abord que vous avez bien utilisé le lien ou le code de parrainage indiqué et que toutes les conditions de l'offre ont été respectées.\n\nSi la prime n'apparaît pas malgré le respect des conditions, contactez directement le partenaire concerné lorsque cela est nécessaire, car c'est lui qui valide généralement l'inscription ou la transaction.\n\nPour le reversement Parrainio, consultez les informations et modalités indiquées sur la fiche de l'offre."],
  ["Où trouver les conditions d'une offre ?", "Les conditions sont indiquées directement sur la fiche de chaque offre Parrainio.\n\nAvant de vous inscrire, prenez quelques secondes pour vérifier les conditions : montant minimum, dépôt, achat, durée, type de compte, code à utiliser ou toute autre condition spécifique.\n\nLes conditions peuvent évoluer : vérifiez toujours les informations affichées au moment de votre inscription."],
] as const;

export default function FAQ() {
  const [open, setOpen] = useState<number | null>(null);
  return <section id="faq" className={styles.section} aria-labelledby="faq-title"><div className={styles.container}><div className={styles.intro}><span className={styles.kicker}>Besoin d&apos;éclaircissements ?</span><h2 id="faq-title">Foire aux <em>questions.</em></h2><p>Tout savoir sur le parrainage et les avantages Parrainio</p></div><div className={styles.list}>{items.map(([question, answer], index) => <div className={`${styles.item} ${open === index ? styles.open : ""}`} key={question}><button className={styles.question} type="button" aria-expanded={open === index} onClick={() => setOpen(open === index ? null : index)}><span>{question}</span><b className={styles.icon} aria-hidden="true">{open === index ? "−" : "+"}</b></button><div className={styles.answer} aria-hidden={open !== index}><div>{answer}</div></div></div>)}</div><p className={styles.footerNote}>Vous ne trouvez pas la réponse à votre question ? Consultez directement les conditions de l&apos;offre qui vous intéresse ou contactez-nous.</p></div></section>;
}
